### ISSUE TITLE
Issue installing dommain-connect in a docker with pip install

### ISSUE THREAD

**Issue by Goodlinux** [Domain-Connect/domainconnect_python#3]
After installing domain-connect 
with 
**pip install domain-connect-dyndns** 

it seams evrything is ok.

"_Installing collected packages: cryptography, publicsuffixlist, domain-connect, domain-connect-dyndns                                  
  Running setup.py install for cryptography ... done                                                                                  
  Running setup.py install for domain-connect-dyndns ... done                                                                         
Successfully installed cryptography-2.8 domain-connect-0.0.6 domain-connect-dyndns-0.0.4 publicsuffixlist-0.6.11_                      
"

but when I try to set up my domain
I have an issue

**domain-connect-dyndns setup --domain xx.domain.me**                                                                                
"
_Traceback (most recent call last):                                                                                                    
  File "/usr/bin/domain-connect-dyndns", line 11, in <module>                                                                         
    load_entry_point('domain-connect-dyndns==0.0.4', 'console_scripts', 'domain-connect-dyndns')()                                    
  File "/usr/lib/python2.7/site-packages/dyndns/command_line.py", line 59, in main                                                    
    print(domain_setup.main(domain, settings))                                                                                        
  File "/usr/lib/python2.7/site-packages/dyndns/domain_setup.py", line 17, in main                                                    
    except NoDomainConnectRecordException or NoDomainConnectSettingsException:                                                        
NameError: global name 'NoDomainConnectRecordException' is not defined_       
"
I didn't find anything whith Google on internet.

**Comment by arnoldblinn** [comment]
In looking at the zone for domain.me, it appears this zone is missing the _domainconnect TXT record.  This can happen if the domain name owner deletes the record manually.

Add the _domainconnect TXT record back in manually.  This shoujld be a TXT record in the zone containing the value: domainconnect.api.secureserver.net

I'm not as familar with this program as Pavel is; he can comment on the xx element of the domain name and if this shoujld work properly.

**Comment by Goodlinux** [comment]
I have set manually a txt record to my domain.me  
![image](https://user-images.githubusercontent.com/880813/67516753-771bf800-f6a1-11e9-8a65-6450bc72d8f7.png)

but the issue is still the same
Thank you by advance for your answers

**Comment by arnoldblinn** [comment]
When I do the query for this record using a public DNS service, the record isn't showing up.  Domain Connect requires this record in order for the DNS Provider to be discovered.  And of course the DNS Provider needs to support domain connect.  Your domain appears to be run by a GoDaddy reseller, which should be supported. But if the app/service can't find the _domainconnect TXT record, it can't run the protocol.

Technically speaking GoDaddy/Secureserver domains have a CNAME in them:

_domainconnect.arnoldblinn-mdd.com. 3600 IN CNAME _domainconnect.ss.domaincontrol.com

Not a _domainconnect TXT record.  But the TXT record should work too....

Without seeing your entire zone it is difficult to diagnose this.  I can look at it next week when I'm back in the office and have access to our internal tools.

Would help to know who you bought the domain through....

**Comment by Goodlinux** [comment]
sorry for the misunderstanding, the real domain I try to setup is ip.maillet.me at ionos provider
the domain is maillet.me

Regards

**Comment by arnoldblinn** [comment]
This misunderstanding forced me to give you some bad advice.  

The _domainconnect TXT record is specific to the DNS Provider.  I have no idea if this was correct or incorrect because you never mentioned this domain name prior.

The proper value for ionos is api.domainconnect.1and1.com

The value you put in there points to SecureServer (GoDaddy Reseller), so things won't work.

**Comment by Goodlinux** [comment]
@arnoldblinn  Thanks a lot, I have put the text and it work perfectly.

**Comment by pawel-kow** [comment]
This one can be closed I believe.

**Comment by Goodlinux** [comment]
Yes thank you

Le mar. 29 oct. 2019 à 13:49, Pawel Kowalik <notifications@github.com> a
écrit :
