### ISSUE TITLE
I can not install it...

### ISSUE THREAD

**Issue by mawa1105** [Domain-Connect/domainconnect_python#6]
Hey,
I got an error , trying to install domain-connect-dyndns on armbian. 

> Command "/usr/bin/python -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-psG4aN --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools>=40.6.0 wheel "cffi>=1.8,!=1.11.3; platform_python_implementation != 'PyPy'"" failed with error code 1 in None

And before:

>      c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory
       #include <Python.h>
                ^~~~~~~~~~
      compilation terminated.
      error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

what can i do?

**Comment by pawel-kow** [comment]
Same as https://github.com/Domain-Connect/DomainConnectDDNS-Python/issues/21 I guess.
Closing.
